### ISSUE TITLE
Problems with ambiguous album titles.

### ISSUE THREAD

**Issue by SarissahSojourner** [emilioastarita/lyricfier#47]
The issue seems to be one that involves an album that is known by more than one name, and labeled so in spotify. So Metallica (also known as The Black Album but not referred to as such) loads lyrics fine, but David Bowie's 2nd album doesn't load any lyrics as it's referred to as "David Bowie (aka Space Oddity)". I know this is kind of an unusual situation as not many album titles have this ambiguity, but there may be a need for some code to help navigate around these unusual special cases.

![screenshot from 2016-12-15 15-38-39](https://cloud.githubusercontent.com/assets/24469189/21243113/ffc3c5d0-c2dc-11e6-87a8-ef71e988544a.png)

**Comment by mrkmndz** [comment]
The services are only queried with artist and song title, so album names don't have an impact on finding lyrics.   In this case the problem is from the fact that the song is Unwashed And Somewhat Slightly Dazed - 2015 Remastered Version, so the "- 2015 Remastered Version" is throwing it off.  @emilioastarita, since these kind of modifiers are almost always at the end we could maybe retry failures repeatedly cutting off the last word, if we don't mind upping our worst case API call count by a factor of the length of song titles.  I guess it depends on the frequency of this kind of modified case.  I would be less inclined to try to special case against dashes or parentheses etc. because then we resign ourselves to keep chasing these bugs forever, because this kind of stuff is in like a million different forms

**Comment by emilioastarita** [comment]
not sure about this idea @mrkmndz. Applying a normalizer for this special cases seems a lot easier than this. In the case that you mention you will be using trying:

```
Unwashed And Somewhat Slightly Dazed - 2015 Remastered Version
Unwashed And Somewhat Slightly Dazed - 2015 Remastered
Unwashed And Somewhat Slightly Dazed - 2015
Unwashed And Somewhat Slightly Dazed
```
Before a successful match ? And what strategie would be good to take with plugins? If you failed to find the first string, you would be trying in the same plugin again cutting off a word or you would be trying with next plugin same string? Seems too complicated to me and I think that the normalized will be working with most songs without adding complexity and network.
