### ISSUE TITLE
Sometimes happens ESOCKETTIMEDOUT

### ISSUE THREAD

**Issue by jsolisu** [emilioastarita/lyricfier#49]
![image](https://cloud.githubusercontent.com/assets/3818673/21468326/fc25499e-c9d0-11e6-86b1-96cffd4a2d28.png)

Spotify version: 1.0.45.186.g3b5036d6
Windows version: 10.0.14393

**Comment by mullerfrederik** [comment]
Same for me. I have (mac) lyricfier version 0.2.4 and spotify version 1.0.45.186.g3b5036d6
I have to quit lyricfier and run again to see lyrics because updates does not work.

![screen shot 2016-12-27 at 13 35 22](https://cloud.githubusercontent.com/assets/23292970/21499813/6cd1a2e0-cc39-11e6-9b6c-5fce0c63f40d.png)

**Comment by emilioastarita** [comment]
this must be fixed on master. can you try please?

**Comment by jsolisu** [comment]
It is fixed.

Thanks.

**Comment by mullerfrederik** [comment]
No, it is not fixed. I still have the same problem.

**Comment by jsolisu** [comment]
@tornisvk with master I don´t have any problem.

**Comment by emilioastarita** [comment]
@tornisvk are you trying with last update on master ? o are you using the last release?

**Comment by mullerfrederik** [comment]
@emilioastarita I am using last release because _npm start_ is not working for me

**Comment by emilioastarita** [comment]
ok. In next release you can try (i think that will be today). btw if you need help with `npm start` open a new issue posting your error. I'm closing this.
