### ISSUE TITLE
connect ECONNREFUSED error

### ISSUE THREAD

**Issue by ghost** [emilioastarita/lyricfier#7]
Hi, when I run this app I get the message "Current song error: Error: connect ECONNREFUSED 127.0.0.1:443" am I missing a step in setting this up?

**Comment by emilioastarita** [comment]
Do you have spotify running ?
Please provide your spotify version and system operative where you are running lyricfier. Thanks for reporting.

**Comment by ghost** [comment]
<img width="1272" alt="screen shot 2016-10-18 at 19 53 05" src="https://cloud.githubusercontent.com/assets/18683608/19491901/8e696f90-956c-11e6-97ac-de44c1ba534f.png">
 Im on Mac OS Sierra, Spotify 1.0.39.157.g674ae377 and runnning Lyricfier just via the release version and not a self build

**Comment by emilioastarita** [comment]
@fedeisas or @silvestreh can you help me debugging the last release on mac? Thanks for reporting @LJAM96 we will be checking this issue this week.

**Comment by emilioastarita** [comment]
@LJAM96 I've added debug lines to the source. Could you clone the repo and run from source code? 

And also I would like to know if you can visit at your browser this URL:

https://open.spotify.com/

If not maybe you have modified your `/etc/hosts` file to point that domain to `127.0.0.1` ? If that the case lyricfier can't work because we need a security token to query the spotify API.

**Comment by ghost** [comment]
Yeah sorry that was my bad didnt think about my hosts file. I checked my hosts file, I was blocking open.spotify.com. The app works brilliantly my bad

**Comment by emilioastarita** [comment]
good to know. closing this!
